
package trainreservation;

import javax.swing.JOptionPane;



public class ReservationMenu extends javax.swing.JFrame {
    
    
    
    
    
    public ReservationMenu() {
        initComponents();
        lbl_about.setVisible(false);
        lbl_close.setVisible(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbl_closepic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_about = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbl_trainpic = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_num2 = new javax.swing.JTextField();
        btn_calc = new javax.swing.JButton();
        radio_A5 = new javax.swing.JRadioButton();
        radio_B4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        radio_slow = new javax.swing.JRadioButton();
        radio_express = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        radio_1st = new javax.swing.JRadioButton();
        radio_2nd = new javax.swing.JRadioButton();
        radio_3rd = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        combo_A5 = new javax.swing.JComboBox<>();
        combo_B4 = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(30, 136, 229));
        jPanel1.setLayout(null);

        lbl_close.setBackground(new java.awt.Color(195, 75, 215));
        lbl_close.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lbl_close.setForeground(new java.awt.Color(178, 178, 178));
        lbl_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_close.setText("Close");
        jPanel1.add(lbl_close);
        lbl_close.setBounds(420, 30, 90, 20);

        jPanel2.setBackground(new java.awt.Color(25, 118, 210));
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(21, 101, 192));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });
        jPanel4.setLayout(null);

        lbl_closepic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_closepic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trainreservation/ic_highlight_off_white_24dp_1x.png"))); // NOI18N
        lbl_closepic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closepicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_closepicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_closepicMouseExited(evt);
            }
        });
        jPanel4.add(lbl_closepic);
        lbl_closepic.setBounds(10, 10, 30, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(465, 0, 50, 50);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Train Ticket Reservation System");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(100, 10, 330, 30);

        lbl_about.setBackground(new java.awt.Color(195, 75, 215));
        lbl_about.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lbl_about.setForeground(new java.awt.Color(178, 178, 178));
        lbl_about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_about.setText("Route Information");
        jPanel2.add(lbl_about);
        lbl_about.setBounds(20, 30, 130, 20);

        jPanel9.setBackground(new java.awt.Color(21, 101, 192));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });
        jPanel9.setLayout(null);

        lbl_trainpic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_trainpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trainreservation/ic_train_white_24dp_1x.png"))); // NOI18N
        lbl_trainpic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_trainpicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_trainpicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_trainpicMouseExited(evt);
            }
        });
        jPanel9.add(lbl_trainpic);
        lbl_trainpic.setBounds(10, 10, 30, 30);

        jPanel2.add(jPanel9);
        jPanel9.setBounds(0, 0, 50, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 515, 50);

        jPanel5.setBackground(new java.awt.Color(30, 136, 229));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Number of Tickets");
        jLabel2.setToolTipText("");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(30, 210, 150, 30);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Route");
        jLabel3.setToolTipText("");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(30, 20, 110, 30);

        txt_num2.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        txt_num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_num2ActionPerformed(evt);
            }
        });
        jPanel5.add(txt_num2);
        txt_num2.setBounds(180, 210, 120, 30);

        btn_calc.setBackground(new java.awt.Color(29, 96, 229));
        btn_calc.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        btn_calc.setForeground(new java.awt.Color(255, 255, 255));
        btn_calc.setText("Calculate");
        btn_calc.setBorderPainted(false);
        btn_calc.setContentAreaFilled(false);
        btn_calc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_calc.setOpaque(true);
        btn_calc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_calcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_calcMouseExited(evt);
            }
        });
        btn_calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcActionPerformed(evt);
            }
        });
        jPanel5.add(btn_calc);
        btn_calc.setBounds(340, 260, 110, 60);

        radio_A5.setBackground(new java.awt.Color(30, 136, 229));
        radio_A5.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        radio_A5.setForeground(new java.awt.Color(255, 255, 255));
        radio_A5.setText("A5");
        radio_A5.setBorder(null);
        radio_A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_A5ActionPerformed(evt);
            }
        });
        jPanel5.add(radio_A5);
        radio_A5.setBounds(170, 20, 80, 30);

        radio_B4.setBackground(new java.awt.Color(30, 136, 229));
        radio_B4.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        radio_B4.setForeground(new java.awt.Color(255, 255, 255));
        radio_B4.setText("B4");
        radio_B4.setBorder(null);
        radio_B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_B4ActionPerformed(evt);
            }
        });
        jPanel5.add(radio_B4);
        radio_B4.setBounds(250, 20, 80, 30);

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Train Type");
        jLabel5.setToolTipText("");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(30, 65, 110, 30);

        radio_slow.setBackground(new java.awt.Color(30, 136, 229));
        radio_slow.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        radio_slow.setForeground(new java.awt.Color(255, 255, 255));
        radio_slow.setText("Slow");
        radio_slow.setBorder(null);
        radio_slow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_slowActionPerformed(evt);
            }
        });
        jPanel5.add(radio_slow);
        radio_slow.setBounds(170, 65, 80, 30);

        radio_express.setBackground(new java.awt.Color(30, 136, 229));
        radio_express.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        radio_express.setForeground(new java.awt.Color(255, 255, 255));
        radio_express.setText("Express");
        radio_express.setBorder(null);
        radio_express.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_expressActionPerformed(evt);
            }
        });
        jPanel5.add(radio_express);
        radio_express.setBounds(250, 65, 80, 30);

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Class Type");
        jLabel6.setToolTipText("");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(30, 110, 110, 30);

        radio_1st.setBackground(new java.awt.Color(30, 136, 229));
        radio_1st.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        radio_1st.setForeground(new java.awt.Color(255, 255, 255));
        radio_1st.setText("1st Class");
        radio_1st.setBorder(null);
        radio_1st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_1stActionPerformed(evt);
            }
        });
        jPanel5.add(radio_1st);
        radio_1st.setBounds(170, 110, 90, 30);

        radio_2nd.setBackground(new java.awt.Color(30, 136, 229));
        radio_2nd.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        radio_2nd.setForeground(new java.awt.Color(255, 255, 255));
        radio_2nd.setText("2nd Class");
        radio_2nd.setBorder(null);
        radio_2nd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_2ndActionPerformed(evt);
            }
        });
        jPanel5.add(radio_2nd);
        radio_2nd.setBounds(270, 110, 90, 30);

        radio_3rd.setBackground(new java.awt.Color(30, 136, 229));
        radio_3rd.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        radio_3rd.setForeground(new java.awt.Color(255, 255, 255));
        radio_3rd.setText("3rd Class");
        radio_3rd.setBorder(null);
        radio_3rd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_3rdActionPerformed(evt);
            }
        });
        jPanel5.add(radio_3rd);
        radio_3rd.setBounds(370, 110, 90, 30);

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Destination");
        jLabel7.setToolTipText("");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(30, 155, 110, 30);

        combo_A5.setBackground(new java.awt.Color(30, 136, 229));
        combo_A5.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        combo_A5.setForeground(new java.awt.Color(255, 255, 255));
        combo_A5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A5 Routes", "A1", "A2", "A3", "A4", "A5" }));
        combo_A5.setBorder(null);
        jPanel5.add(combo_A5);
        combo_A5.setBounds(170, 155, 100, 30);

        combo_B4.setBackground(new java.awt.Color(30, 136, 229));
        combo_B4.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        combo_B4.setForeground(new java.awt.Color(255, 255, 255));
        combo_B4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B4 Routes", "B1", "B2", "B3", "B4" }));
        combo_B4.setBorder(null);
        jPanel5.add(combo_B4);
        combo_B4.setBounds(280, 155, 100, 30);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 50, 515, 350);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 400);

        setSize(new java.awt.Dimension(515, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        new T_Info().setVisible(true);
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        lbl_about.setVisible(true);
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        lbl_about.setVisible(false);
    }//GEN-LAST:event_jPanel9MouseExited

    private void lbl_closepicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closepicMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbl_closepicMouseClicked

    private void lbl_closepicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closepicMouseEntered
        lbl_close.setVisible(true);
    }//GEN-LAST:event_lbl_closepicMouseEntered

    private void lbl_closepicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closepicMouseExited
        lbl_close.setVisible(false);
    }//GEN-LAST:event_lbl_closepicMouseExited

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        this.dispose();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        lbl_close.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        lbl_close.setVisible(false);
     
    }//GEN-LAST:event_jPanel4MouseExited

    private void txt_num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_num2ActionPerformed

    private void btn_calcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calcMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_calcMouseEntered

    private void btn_calcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calcMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_calcMouseExited

    private void btn_calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcActionPerformed

                  
        try{
           
            //show the answer form
            this.dispose();
            new TotalView().setVisible(true);
        }
        
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "Fill the text Feilds correctly..!", "Error!", JOptionPane.WARNING_MESSAGE);
            
        }
            
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Fill the text Feilds correctly..!", "Error!", JOptionPane.WARNING_MESSAGE);
           
        }
                 
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error..!", "Error!", JOptionPane.ERROR_MESSAGE);
            
        }
            
 
        
    }//GEN-LAST:event_btn_calcActionPerformed

    private void lbl_trainpicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_trainpicMouseClicked
        new T_Info().setVisible(true);
    }//GEN-LAST:event_lbl_trainpicMouseClicked

    private void lbl_trainpicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_trainpicMouseEntered
        lbl_about.setVisible(true);
    }//GEN-LAST:event_lbl_trainpicMouseEntered

    private void lbl_trainpicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_trainpicMouseExited
        lbl_about.setVisible(false);
    }//GEN-LAST:event_lbl_trainpicMouseExited

    private void radio_A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_A5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_A5ActionPerformed

    private void radio_B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_B4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_B4ActionPerformed

    private void radio_slowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_slowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_slowActionPerformed

    private void radio_expressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_expressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_expressActionPerformed

    private void radio_1stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_1stActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_1stActionPerformed

    private void radio_2ndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_2ndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_2ndActionPerformed

    private void radio_3rdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_3rdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_3rdActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calc;
    private javax.swing.JComboBox<String> combo_A5;
    private javax.swing.JComboBox<String> combo_B4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_about;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_closepic;
    private javax.swing.JLabel lbl_trainpic;
    private javax.swing.JRadioButton radio_1st;
    private javax.swing.JRadioButton radio_2nd;
    private javax.swing.JRadioButton radio_3rd;
    private javax.swing.JRadioButton radio_A5;
    private javax.swing.JRadioButton radio_B4;
    private javax.swing.JRadioButton radio_express;
    private javax.swing.JRadioButton radio_slow;
    private javax.swing.JTextField txt_num2;
    // End of variables declaration//GEN-END:variables
}
